### ISSUE TITLE
Random colorisation samples N^2 pixels

### ISSUE THREAD

**Issue by zellaa** [bennm37/image_colourisation#6]
Need to find a fast way to get N samples, or maybe change label.

**Comment by bennm37** [comment]
Potentially generate a sample once at the beggining and store it? Then choosing which pixels is just a case of getting  the first N stored indicies? Regenerate Button as well for a new sample ?
Also happy to just drop the slider that and have a set number.

**Comment by zellaa** [comment]
Resolved in 2f02d3c5a4c890677760555487e263c7bb217cfa.
