### ISSUE TITLE
Stylise selectedColor123 Buttons

### ISSUE THREAD

**Issue by bennm37** [bennm37/image_colourisation#8]
Currently using square tkinter frames with black and red backgrounds that look a bit btec. Maybe rounded corners and nicer background colors would help? These are also the cause of the flashing bug.

**Comment by zellaa** [comment]
So the buttons are now rounded and the highlight color/background color are in line with the overall dark scheme. 
![ss](https://user-images.githubusercontent.com/49277675/216306001-f965307b-fdb8-4932-925b-0a7fd3a038f0.png)

There's still that weird color area thing where its got white borders on my machine.

**Comment by bennm37** [comment]
Amazing! Yeah we should sort that whitespace today. I've change the layout  (+bg color to match the rest of sidebard) of that section a fair bit so lets merge first and then sort any asthetics after that if that's good?

**Comment by bennm37** [comment]
Remove selectedColorButtonBackground (frames)
